project:
  type: book
  output-dir: _book
  
execute:
  freeze: auto

version: "0.0.2"

book:
  page-footer:
    center: 
      - text: "License"
        href: license.qmd
  title: "Semantic Stabilisation"
  subtitle: "A Pragmatic Research and Innovation Programme"
  downloads: [pdf, epub, docx] 
  output-file: semantic-stabilisation-v002
  author:
     - name: "Daniel Antal, CFA"
       orcid: 0000-0001-7513-6760
       affiliations:
               - name: Reprex
                 address: "Saturnusstraat 14"
                 city: The Hague
                 state: Zuid-Holland
                 country: The Netherlands
                 postal-code: "2516 AH"
  date: "2026-06-14"
  repo-url: https://github.com/dataobservatory-eu/semantic-stabilisation
  repo-actions: [edit]
  chapters:
    - index.qmd
    - glossary.qmd
    - innovation.qmd
    - empirical.qmd
    - projects.qmd
    - research.qmd
    - references.qmd

citation:
  container-title: "Semantic Stabilisation"
  doi: "10.5281/zenodo.18094885"
  url: https://downloads.reprex.nl/2026/semantic-stabilistaion/

bibliography: 
    - bib/aibusiness.bib
    - bib/antal.bib
    - bib/BVDA.bib
    - bib/eccch.bib
    - bib/datainteroperability.bib
    - bib/datamodels.bib
    - bib/dataspace.bib
    - bib/decolonisation.bib
    - bib/CISAC.bib
    - bib/collections.bib
    - bib/eulaw.bib
    - bib/eupolicies.bib
    - bib/europeana.bib
    - bib/eXtremeDesign.bib
    - bib/grd.bib
    - bib/identifiers.bib
    - bib/IFPI.bib
    - bib/ISOData.bib
    - bib/metadata.bib
    - bib/MLC.bib
    - bib/mme.bib
    - bib/musicindustry.bib
    - bib/musicmetadata.bib
    - bib/ontologies.bib
    - bib/opa.bib
    - bib/opendata.bib
    - bib/OpenMusE.bib
    - bib/openmusicobservatory.bib
    - bib/openmusicrepositories.bib
    - bib/ric.bib
    - bib/services.bib
    - bib/trustworthyAI.bib
    - bib/wikidata.bib
    
csl: csl/chicago-author-date-17th-edition.csl

papersize: a4 
  
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    classoption:
      - paper=a4
      - oneside
      - pagesize
      - BCOR=0mm
      - DIV=13   # try 12–13 for ~25 mm; 14–15 for ~20 mm
    fontsize: 12pt
  epub: default 
  docx: default

editor: visual

